apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-service-monitor
  namespace: monitoring-demo
  labels:
    team: platform
    app: java-service
spec:
  selector:
    matchLabels:
      app: java-service
  namespaceSelector:
    matchNames:
      - monitoring-demo
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
          replacement: monitoring-demo
        - targetLabel: cluster
          replacement: prom-demo