apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
    team: platform
spec:

  namespaceSelector:
    matchNames:
      - monitoring-demo

  selector:
    matchLabels:
      app: java-service

  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s

      relabelings:
        - sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: namespace

        - sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: pod

        - sourceLabels:
            - __meta_kubernetes_service_name
          targetLabel: service