apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-service-monitor
  namespace: monitoring-demo
  labels:
    team: platform
    app: python-service
spec:
  selector:
    matchLabels:
      app: python-service
  namespaceSelector:
    matchNames:
      - monitoring-demo
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
          replacement: monitoring-demo
        - targetLabel: cluster
          replacement: prom-demo